name: ActionBarBroadcast
main: net.pekkit.actionbarbroadcast.ActionBarBroadcast
version: maven-version-number
description: ActionBarBroadcast
author: Squawkers13
website: http://www.spigotmc.org/resources/actionbarbroadcast.2398/
commands:
    ab:
      aliases: [actionbar, actionbarbroadcast]
      description: Base command for ActionBarBroadcast.
    broadcast:
      aliases: [bc, bcast]
      description: Broadcast a message to all online players.
permissions:
    actionbarbroadcast.broadcast:
        description: Broadcast a message.
        default: op
    actionbarbroadcast.reload:
        description: Reload the plugin's configuration.
        default: op